### ISSUE TITLE
点击关闭按钮后，如何让他再次显示？

### ISSUE THREAD

**Issue by sbwml** [stevenjoezhang/live2d-widget#1]
如题，是不是如果关闭，是不是每次都要清理浏览器缓存才能重新显示？

**Comment by stevenjoezhang** [comment]
目前的逻辑是关闭之后一天之内不再显示。当然，也可以有更好的解决方案，欢迎提出建议。

**Comment by sbwml** [comment]
关闭后重新再显示的时间可以自定义的吗？

**Comment by stevenjoezhang** [comment]
目前还不能……我明（今）天更新一下，加一个可选参数进去

**Comment by sbwml** [comment]
靠谱，期待你的更新

**Comment by stevenjoezhang** [comment]
咕咕咕，可能还要一些时间……我准备把所有允许用户自定义的参数用一个json传进去，包括显示哪些按钮、关闭后重新再显示的时间、加载的api地址等等，会是一次大更新

**Comment by watchXdog** [comment]
为什么我的点击关闭后就无法再次显示 你的博客可以呢??

**Comment by stevenjoezhang** [comment]
@sbwml @watchXdog 这个功能加了：https://github.com/stevenjoezhang/live2d-widget/commit/05cc012374a4b0e85fd1470063082b8f835e264b
