### ISSUE TITLE
怎么才能让看板娘显示在右下角或者说可以拖动

### ISSUE THREAD

**Issue by NiTian1207** [stevenjoezhang/live2d-widget#10]
求助

**Comment by stevenjoezhang** [comment]
可以修改 CSS 实现，但是牵扯的地方有点多。

**Comment by stevenjoezhang** [comment]
感谢建议，已增加拖动功能 https://github.com/stevenjoezhang/live2d-widget/commit/aae552759611e205fb8d5a49f0349f2630bc0d1c
