### ISSUE TITLE
调整到2147483647仍然遮挡

### ISSUE THREAD

**Issue by lzhvahaha** [stevenjoezhang/live2d-widget#103]
使用fluid主题
![image](https://user-images.githubusercontent.com/102528913/165440759-6cbc3dad-5c4e-439d-b717-b011b7e03c99.png)

**Comment by stevenjoezhang** [comment]
请提供网站链接

**Comment by lvhejin** [comment]
找不到在哪里配置Z轴？

**Comment by stevenjoezhang** [comment]
参考 #96 
如果不行的话，可能需要修改 fluid 主题的样式文件
