### ISSUE TITLE
作者您好，请问如何修改看板娘的模型？

### ISSUE THREAD

**Issue by xieyanshe666** [stevenjoezhang/live2d-widget#104]
想改成坐在碗中的小狗的

**Comment by LuckyEnough-Z** [comment]
> 使用 https://github.com/fghrsh/live2d_api 搭建后端 api，添加自己想要的模型，并将
> 
> https://github.com/stevenjoezhang/live2d-widget/blob/865ecc50da158fdf050dbdb442a97aeb1af4bd06/autoload.js#L36
> 
> 修改为自己的 api

你好，我搭建了，导入模型后不显示角色，与目录自带的模型相比目录结构不同，但是修改后依然无法正常显示，请问有考虑过出个适配教程吗

**Comment by PFiS1737** [comment]
由下面的 L216 和 L218 可以看到，live2d 的加载是通过将 api 传入一个全局的 loadlive2d 方法实现的。

https://github.com/stevenjoezhang/live2d-widget/blob/cfafafaa51f9eb50d8cb9e309495f6bc06b567a9/waifu-tips.js#L213-L220

而这个方法是 [live2d.min.js](https://github.com/stevenjoezhang/live2d-widget/blob/master/live2d.min.js) 提供的，但是这个文件经过了加密，并不能提供有效参考。  
所以还是尽量按照 [live2d_api](https://github.com/fghrsh/live2d_api) 里的结构来吧。而且根据 #66 ，目前是不支持 v3 的模型的。

**Comment by LuckyEnough-Z** [comment]
> 由下面的 L216 和 L218 可以看到，live2d 的加载是通过将 api 传入一个全局的 loadlive2d 方法实现的。
> 
> https://github.com/stevenjoezhang/live2d-widget/blob/cfafafaa51f9eb50d8cb9e309495f6bc06b567a9/waifu-tips.js#L213-L220
> 
> 而这个方法是 [live2d.min.js](https://github.com/stevenjoezhang/live2d-widget/blob/master/live2d.min.js) 提供的，但是这个文件经过了加密，并不能提供有效参考。 所以还是尽量按照 [live2d_api](https://github.com/fghrsh/live2d_api) 里的结构来吧。而且根据 #66 ，目前是不支持 v3 的模型的。

解决了，还有一点就是想问问为什么看板娘会随着我点击菜单栏的标签而刷新，请问如何关闭看板娘随着点击标签页刷新

**Comment by stevenjoezhang** [comment]
@LuckyEnough-Z 你可以检查一下是不是 Pjax 之类的刷新配置有问题，点击标签页之后看板娘可能被重新加载了
