### ISSUE TITLE
作者您好，如果想把看板娘作为头像(就像您login示例中的一样)应该怎么修改

### ISSUE THREAD

**Issue by Jackylee06** [stevenjoezhang/live2d-widget#106]
(我用的是hexo，next主题)

**Comment by Jackylee06** [comment]
![微信图片_20220520235237](https://user-images.githubusercontent.com/78067745/169566532-ad70003c-9974-44a5-8c04-9b787271ba9b.png)
感谢解答
因为实在是没学过，我就把demo里的文件拆吧拆吧改了几下直接复制上去了
果然出现了问题。。。

1. 模型的位置是歪的
2. 网页上半部分翻不上去，底部的文字被挤到旁边了

还是等回头有时间学一下相关的知识再说吧

**Comment by stevenjoezhang** [comment]
Issue 先关了，有其他问题欢迎继续讨论
