### ISSUE TITLE
Jsdeliver的CDN不能访问

### ISSUE THREAD

**Issue by MUYIio** [stevenjoezhang/live2d-widget#107]
作者您好！https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js无法访问导致不能正常显示，但是我把这个jquery.min.js放到主题里再引用网站一部分内容也就无法显示了，请问该怎么弄呢，谢谢！

**Comment by PFiS1737** [comment]
1. jsdelivr 的 cdn 国内经常出现不能访问的问题，可以考虑把文件下载下来放到网站目录中，或使用其他 cdn
2. 我寻思这个项目也没用到 jq 呀，为什么要在这里问

**Comment by stevenjoezhang** [comment]
是的，本项目并没有加载 jQuery
CDN 链接已更新： https://github.com/stevenjoezhang/live2d-widget/commit/cfafafaa51f9eb50d8cb9e309495f6bc06b567a9
