### ISSUE TITLE
live2d.min.js source code 源码

### ISSUE THREAD

**Issue by shen076** [stevenjoezhang/live2d-widget#11]
请问大佬 live2d.min.js 源码，没打包过的版本，有吗？（不单指压缩。）

**Comment by stevenjoezhang** [comment]
看README嘛：https://github.com/stevenjoezhang/live2d-widget#%E6%9B%B4%E5%A4%9A-more

**Comment by shen076** [comment]
> 看README嘛：https://github.com/stevenjoezhang/live2d-widget#%E6%9B%B4%E5%A4%9A-more

thanks
