### ISSUE TITLE
工具栏是横着的

### ISSUE THREAD

**Issue by Macesuted012** [stevenjoezhang/live2d-widget#113]
![image](https://user-images.githubusercontent.com/98137829/180206024-36660e12-be16-4387-aebd-197bcc40b7c6.png)
请问这是为什么？

**Comment by Macesuted012** [comment]
自己解决了，给大家点经验
fontawesome图标的Technology选项只能选Web Font不能选SVG

**Comment by stevenjoezhang** [comment]
是的，SVG 可能会和工具栏的样式冲突。
