### ISSUE TITLE
如何改为加载静态图片

### ISSUE THREAD

**Issue by XuanDe-HK** [stevenjoezhang/live2d-widget#114]
能否修改loadlive2d的方式，加载放上去的静态png图片，要不然cdn记载的太慢了，有时候甚至根本加载不出来

**Comment by PFiS1737** [comment]
在 autoload.js 中使用 
apiPath，而不是 cdnPath。
https://github.com/stevenjoezhang/live2d-widget/blob/cfafafaa51f9eb50d8cb9e309495f6bc06b567a9/autoload.js#L36-L37
api 格式见 https://github.com/fghrsh/live2d_api

**Comment by XuanDe-HK** [comment]
谢谢能抽空回答我的问题，但apiPath有的时候也会访问不了，所以我想把调用模型从后端api改为代用本地的静态资源，也就是牺牲换模型和皮肤的功能，只保留一个模型
比如调用网址是：https://cdn.jsdelivr.net/gh/fghrsh/live2d_api@1.0.1/model/Potion-Maker/Pio/textures/default-costume.png
我想改为从本地调用，类似于：/images/default-costume.png这种

**Comment by PFiS1737** [comment]
既然有本地运行环境，就把 https://github.com/fghrsh/live2d_api 里的东西全下载到本地，在 cdnPath 上填入对应地址就行了，就不用考虑第三方 cdn 不稳定的问题了。
（另外是去简单学习下 js，代码能读懂，基本上问题就解决了

**Comment by stevenjoezhang** [comment]
简单的做法是，准备好一个 `model_list.json`，只定义一个模型，然后在模型的 `index.json` 里面把 `textures` （图片路径）设置为 `/images/default-costume.png`
