### ISSUE TITLE
看板娘无法正常加载

### ISSUE THREAD

**Issue by muxinchn** [stevenjoezhang/live2d-widget#115]
如题，无法正常加载模型，但是右侧的按钮和上面的对话框可以正常加载。怀疑是CDN的问题，因为jsdelivr在中国大陆的许可证被吊销了。

**Comment by conan1994** [comment]
我也是这样

**Comment by SaraKale** [comment]
好像elemecdn恢复了，可以用npm.elemecdn.com的~或者unpkg也可以

**Comment by stevenjoezhang** [comment]
是的，大家根据自己的情况选择一个合适的 CDN 服务即可～
