### ISSUE TITLE
[feature] 重构后本地调试更困难

### ISSUE THREAD

**Issue by Hugh357** [stevenjoezhang/live2d-widget#121]
有一说一，这次重构后代码解耦了，结构更清晰，但是不方便调试。

在以前，我自定义看板娘，只需把`waifu-tips.js` `waifu-tips.json` `autoload.js`放在自己网站目录下，在`autoload.js`中更改前面两者的地址即可。本地调试我修改文件后硬性刷新网页即可。

现在我要本地调试，正常需要下面几步

1. 除了网站要起http服务，看板娘也要起一个http服务
2. 网站本地调试时，`autoload.js`的地址不能是`/js/autoload.js`这种相对路径，也不能是生产、部署环境中的cdn地址，而是我本地的另一个端口。也就是**本地调试和生产环境的`autoload.js`地址不同**，每次都要切换。
3. 看板娘文件更新后，需要`npm run build`重新构建

希望可以优化一下步骤，毕竟fork的人还是挺多的

我发现一个方法可以轻松一点，分享一下：

像以前一样把`waifu-tips.js` `waifu-tips.json` `autoload.js`放在自己网站目录下

`waifu-tips.js`如何放到网站根目录呢？修改package.json

```
  "scripts": {
    "build": "rollup -c rollup.config.js -f iife | terser -c -m > /waifu-tips.js",
    "debug": "rollup -c rollup.config.js -f iife | terser -c -m > ../site-project-dir/static/js/waifu-tips.js"
  }
```

添加一个脚本，将文件输出到网站项目目录下，这样我之前说的需要三步，就变成了需要`npm run debug`这一步

顺便问一下，以前消息中`<span>`是蓝色字体，现在没了，不知道是bug还是特性？

**Comment by stevenjoezhang** [comment]
谢谢反馈，`span` 的颜色问题应该是 1959d0742956c8843ea3b74af167271673e10b4a 这个 commit 里面改坏了，现已修复。

本地调试时可以像这样：

```
rollup -c rollup.config.js -f iife -o ../site-project-dir/static/js/waifu-tips.js -w
```

把这个命令挂在后台执行，`-w` 选项会 watch 文件的变更，自动重新生成。你看看这样是不是方便一点。

**Comment by Hugh357** [comment]
好的，谢谢
