### ISSUE TITLE
关了梯子以后  raw.githubusercontent.com资源访问不了呢

### ISSUE THREAD

**Issue by Goobercute** [stevenjoezhang/live2d-widget#123]
![image](https://user-images.githubusercontent.com/34137206/199188054-e6626710-c2cb-422c-80af-e0c2676ca2c1.png)

**Comment by Goobercute** [comment]
好像是301 重定向到github资源的时候。没有加速器

**Comment by stevenjoezhang** [comment]
昨天我也发现这个问题了，今天似乎恢复了。状态码 200，没有重定向，这样是正常加载的。
