### ISSUE TITLE
[萌新]关于模型不显示的问题向作者请教

### ISSUE THREAD

**Issue by uncoveredfigure** [stevenjoezhang/live2d-widget#126]
如下图，文本和工具框都能正常显示，我把所有提问都翻找并尝试复现但都没有解决问题，最近的一个解答提到CDN问题，所以向作者确认问题根源以及如何更改CDN
<img width="225" alt="1" src="https://user-images.githubusercontent.com/91234861/210599552-8ef37a30-2458-4346-8a2c-3499fe13a75a.PNG">

**Comment by stevenjoezhang** [comment]
可以提供一下你的网站链接吗

**Comment by uncoveredfigure** [comment]
> 可以提供一下你的网站链接吗

麻烦了，https://63b677a04fb5756c84c5844e--famous-tapioca-be851e.netlify.app/，我平时在GitHub pages（https://uncoveredfigure.github.io/）上托管，但目前GitHub pages网站还没有更新

**Comment by stevenjoezhang** [comment]
<img width="983" alt="截屏2023-01-05 16 24 33" src="https://user-images.githubusercontent.com/16272760/210734642-b097bb18-3579-4d3b-a3c7-e1829e30af11.png">

我这好像没问题。应该也不是 CDN 的问题，否则文本和工具框也无法加载出来

**Comment by uncoveredfigure** [comment]
了解了，我刚刚又尝试了一次，虽然还是没有显示出来
<img width="1280" alt="无标题" src="https://user-images.githubusercontent.com/91234861/210743022-f4e55390-fb67-4784-8a7c-93781d84d036.png">

**Comment by stevenjoezhang** [comment]
你可以试试清除浏览器缓存、换一个浏览器、换一个网络环境（比如开手机热点），看能不能加载
如果还是不行，就设置一下这个 

https://github.com/stevenjoezhang/live2d-widget/blob/ae27493c29391e0cf2e9c08d27ab9d466f0a9c93/autoload.js#L37-L38

取消注释 `apiPath`，注释 `cdnPath`

**Comment by uncoveredfigure** [comment]
我一一尝试了以上所以方法（浏览器由edge换成谷歌），很遗憾还是没有解决问题，这令我抓狂，目前假定只有本机访问该网站出现此问题，在我眼里自己现在已经无药可救了，无论是否还有别的方法，在此先向作者的耐心致敬

**Comment by cvpv** [comment]
为什么不把所有资源都下载到本地呢，我没有深究该项目，不太清楚为什么没有这么做

**Comment by drowning-in-codes** [comment]
现在4.26日 我这边大陆使用cdn又可以显示了,之前确实cdn可能被污染大陆无法访问。
如果自己有服务器,也可自己搭建api
