### ISSUE TITLE
模型图片无法显示

### ISSUE THREAD

**Issue by khan-yin** [stevenjoezhang/live2d-widget#127]
作者好，国内访问模型似乎被屏蔽了，如果挂vpn访问能正常显示，请问有办法解决吗
![image](https://user-images.githubusercontent.com/50772219/212069532-f24bfc3a-af9e-4a4c-a006-e443a317d57d.png)
![image](https://user-images.githubusercontent.com/50772219/212069656-e935061f-3ebe-40dd-bfd5-10e6436b2de6.png)

**Comment by duanjr** [comment]
https://duanjinrong.com/article/41f6850c-35ff-408d-9596-0ec057048165
可以使用我的后端接口

**Comment by LQY679** [comment]
这个问题更换成国内镜像源就好, 在autoload.js中将apiPath的值修改为"https://api.zsq.im/live2d" , 这个亲测可以用 ,
