### ISSUE TITLE
关于触发条件

### ISSUE THREAD

**Issue by kostya-sec** [stevenjoezhang/live2d-widget#138]
hello，作者你好。触发条件的内容能动态修改吗

**Comment by stevenjoezhang** [comment]
能具体说下要达到什么效果吗？

**Comment by kostya-sec** [comment]
我想加的一些比如我给他一些input，然后后端会返回output。然后将新的output作为触发条件的内容展示

**Comment by stevenjoezhang** [comment]
触发条件都在一个 json 里，让后端根据需求拼接好这个 json 之后加载就行
