### ISSUE TITLE
不支持手机平台吗

### ISSUE THREAD

**Issue by redXpanda** [stevenjoezhang/live2d-widget#14]
试了一下iphone和一台魅族，都显示不出来。

**Comment by stevenjoezhang** [comment]
https://github.com/stevenjoezhang/live2d-widget/blob/e89dde2466c58ba1f1fb08062ec1d8a21bdba740/waifu-tips.js#L225

**Comment by redXpanda** [comment]
好的，谢谢。再问一个问题，我也出现了一个Uncaught ReferenceError: initWidget is not defined
然后刷新了几次变成了新的错误，live2d框架加载出来了但是模型加载错误，点UI上换个人物，倒是出来了。再刷新几次，就又是Uncaught ReferenceError: initWidget is not defined了。编码都是UTF-8，format都是unix，浏览器直接访问会有中文乱码，但是文件本身用NOTEPAD++访问是没有问题的，总之感觉不像是编码问题.项目也在linux上重新clone过去了，还是不行。

**Comment by redXpanda** [comment]
我把autoload里的加载搬到html里，好了。对前端技术并不是很懂，如果大佬有空的话可以看看是咋回事

**Comment by stevenjoezhang** [comment]
`initWidget is not defined`的问题应该解决了： https://github.com/stevenjoezhang/live2d-widget/pull/12

**Comment by stevenjoezhang** [comment]
@redXpanda 问题解决了么？

**Comment by redXpanda** [comment]
见2019年11月的评论，我把autoload里的加载搬到html里，好了

**Comment by stevenjoezhang** [comment]
解决了就好，有其他问题欢迎提出

**Comment by stevenjoezhang** [comment]
对于屏幕宽度的判断修改了位置： https://github.com/stevenjoezhang/live2d-widget/commit/e4037cdcd6fd562a97afb4203553cc09f1a2b392
这样更方便自定义且节省计算资源

**Comment by wei-z-git** [comment]
> 对于屏幕宽度的判断修改了位置： [e4037cd](https://github.com/stevenjoezhang/live2d-widget/commit/e4037cdcd6fd562a97afb4203553cc09f1a2b392)
> 这样更方便自定义且节省计算资源

有个疑惑。。autoload.js加上宽度限制的话手机端不就不去加载资源了7c604ae

**Comment by KnowsCount** [comment]
> > 对于屏幕宽度的判断修改了位置： [e4037cd](https://github.com/stevenjoezhang/live2d-widget/commit/e4037cdcd6fd562a97afb4203553cc09f1a2b392)
> > 这样更方便自定义且节省计算资源
> 
> 有个疑惑。。autoload.js加上宽度限制的话手机端不就不去加载资源了 [[e4037cd](https://github.com/stevenjoezhang/live2d-widget/commit/e4037cdcd6fd562a97afb4203553cc09f1a2b392)]

---

应该是这么个意思。根据我对如下 snippet 的理解：

```
if (screen.width >= 768) {
 	Promise.all([
 		loadExternalResource(live2d_path + "waifu.css", "css"),
 		loadExternalResource(live2d_path + "live2d.min.js", "js"),
 		loadExternalResource(live2d_path + "waifu-tips.js", "js")
 	]).then(() => {
 		initWidget(live2d_path + "waifu-tips.json", "https://live2d.fghrsh.net/api");
 	});
 }
```

是只有在 `(screen.width >= 768)` 时才会加载底下内容的。

所以……应该吧 `if` 给去掉就可以在手机端加载资源了？
