### ISSUE TITLE
提供一个有趣的建议

### ISSUE THREAD

**Issue by Zhuying-Net** [stevenjoezhang/live2d-widget#151]
尊敬的作者您好，我有一个有趣的想法，将看板娘搭配GPT实现模拟动漫人物的效果。那么应该会很有趣。可以提供各种关于AI模型的api，到时候不仅可以实现对话，绘图说不定都可以

**Comment by stevenjoezhang** [comment]
谢谢反馈，相关功能已在开发。请不要提供其它平台的广告。
