### ISSUE TITLE
你好，请问你这个能发布到greasyfok吗

### ISSUE THREAD

**Issue by Renjh5218** [stevenjoezhang/live2d-widget#155]
这个不能更新了![Screenshot_2023-12-18-06-12-03-42_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/stevenjoezhang/live2d-widget/assets/79973902/8f1e55e5-aade-4daa-894b-ed358a93ce3d)

**Comment by stevenjoezhang** [comment]
没有计划发布到greasyfok上。这个仓库的代码主要计划提供给网站管理员使用，浏览器插件并不是预期使用场景。
