### ISSUE TITLE
Broken demo links in README

### ISSUE THREAD

**Issue by nkh0472** [stevenjoezhang/live2d-widget#156]
404 error in the following links in [README.md](https://github.com/stevenjoezhang/live2d-widget/blob/master/README.md) as well as in [README.en.md](https://github.com/stevenjoezhang/live2d-widget/blob/master/README.en.md):
> [demo.html](https://mi.js.org/live2d-widget/demo/demo.html)，展现基础功能
> [login.html](https://mi.js.org/live2d-widget/demo/login.html)，仿 NPM 的登陆界面

**Comment by MliKiowa** [comment]
```
https://stevenjoezhang.github.io/live2d-widget/demo/demo.html
https://stevenjoezhang.github.io/live2d-widget/demo/login.html
```

**Comment by stevenjoezhang** [comment]
谢谢反馈，我在 js.org 注册的子域名不知道怎么没有了😂

**Comment by MliKiowa** [comment]
> 谢谢反馈，我在 js.org 注册的子域名不知道怎么没有了😂

🤣🤣🤣看了下好像还在 js.org git仓库里面记录的也是你的 但是确实域名进去页面不是你的

**Comment by stevenjoezhang** [comment]
绷不住了，说明了域名自主可控的重要性 🤣

**Comment by MliKiowa** [comment]
> 绷不住了，说明了域名自主可控的重要性 🤣

🤣👍 自己域名可以的 免费剽的还是有风险的 那天切了都不知道。
总结下 很想笑，不过你应该提个issue我挺好奇什么原因的
