### ISSUE TITLE
看板娘欢迎语识别为空白？

### ISSUE THREAD

**Issue by hzp2333** [stevenjoezhang/live2d-widget#158]
感谢大佬的开发。使用的最简单的方法，在页面部分加入
`<script src="https://fastly.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/autoload.js"></script>`
在对应页面部分。看板娘本来会说“欢迎阅读《xxx》”
但是最近不知为何都变成了空白，变成了欢迎阅读《》。
请问是哪里进行这类识别？有什么检查配置的方法呢？感谢！

![Uploading Screenshot_20240305_012441_com.microsoft.emmx.jpg…]()

**Comment by stevenjoezhang** [comment]
你能提供一下出问题的网站链接吗？

**Comment by hzp2333** [comment]
> 你能提供一下出问题的网站链接吗？

blog.huaxiangshan.com 十分感谢您！

**Comment by stevenjoezhang** [comment]
不客气，您的网站代码不完整（缺少`<html><head>`等等），因此获取不到`document.title`。可以检查一下是不是生成的时候出错了。

<img width="565" alt="截屏2024-03-05 13 57 46" src="https://github.com/stevenjoezhang/live2d-widget/assets/16272760/65e6efa3-0b4f-4be1-adbe-ffd2c0993b17">
