### ISSUE TITLE
npm run problem help!

### ISSUE THREAD

**Issue by luis170202** [stevenjoezhang/live2d-widget#169]
npm run problem
![Captura de pantalla 2024-08-07 204315](https://github.com/user-attachments/assets/dcb4531d-6e58-46e8-a3fd-46f1a5daf929)

**Comment by EchoHayate** [comment]
same

**Comment by stevenjoezhang** [comment]
I tested the `npm run build` script on Windows, and it successfully generated `waifu-tips.js`. Please provide more information if the problem persists.
