### ISSUE TITLE
是否有看板娘全部完成的回调方法

### ISSUE THREAD

**Issue by Y00z** [stevenjoezhang/live2d-widget#17]
我这边加了一个拖动看板娘的js，但是绘制看板娘是异步加载的，没发判断看板娘是否绘画完成，拿到的waifu是空的，可否加一个看板娘绘画完成的回调方法？

**Comment by stevenjoezhang** [comment]
> 可否加一个看板娘绘画完成的回调方法？

恐怕不能，这个绘画完成事件的相关代码版权属于 Live2D Inc. ，修改后传播存在法律风险： https://github.com/stevenjoezhang/live2d-widget#许可证-license

当然，你可以自己修改代码。需要将`live2d.min.js`格式化，然后找到如下代码

<img width="1352" alt="截屏2020-02-01下午2 08 41" src="https://user-images.githubusercontent.com/16272760/73587892-5c58eb00-44fc-11ea-9bef-a676b5d73107.png">

通过监听这个 `onload` 事件来确定材质已经加载完成。

**Comment by stevenjoezhang** [comment]
最近我进行了大范围的代码重构，现在将看板娘加载方法改为了 async 函数，await 一下就可以等待加载完成。欢迎试用～
