### ISSUE TITLE
xhr请求太多了, 影响到了调试, 怎么破?

### ISSUE THREAD

**Issue by sidian123** [stevenjoezhang/live2d-widget#18]
<img width="530" alt="批注 2020-02-05 184410" src="https://user-images.githubusercontent.com/44724649/73835113-d4e6e100-4847-11ea-9d11-ec1f0817960a.png">

如图, 一直在请求着

**Comment by stevenjoezhang** [comment]
这个无解，可以切换一个资源少一点的模型试试。

**Comment by sjlei** [comment]
Filter


![Snipaste_2021-03-30_14-54-09](https://user-images.githubusercontent.com/34293221/112946292-eab01780-9167-11eb-85fc-16df67454b41.png)


![Snipaste_2021-03-30_14-53-41](https://user-images.githubusercontent.com/34293221/112946283-e97eea80-9167-11eb-9228-f94ca3e65522.png)

**Comment by stevenjoezhang** [comment]
最近我进行了大范围的代码重构，现在可以用上缓存了，不会再出现很多http请求，欢迎试用～
