### ISSUE TITLE
关于加载模型的方式

### ISSUE THREAD

**Issue by wu-kan** [stevenjoezhang/live2d-widget#19]
目前想要加载自定义模型要自己搭后端，感觉不太方便。能否修改成通过这个[live2d-helper](https://www.npmjs.com/package/live2d-helper)或者类似的方式加载模型？这样既不用自己搭后端，也可以通过jsdelivr之类的cdn加速live2d贴图的访问。

换成html代码大概长下面这个样子。

```html
<script
  defer="defer"
  src="https://cdn.jsdelivr.net/npm/live2d-helper@1.0.0/dist/index.min.js"
  onload='if (screen.width >= 768) {
    document.body.insertAdjacentHTML("beforeend", `
      <div id="waifu">
        <canvas id="live2d"></canvas>
      </div>`);
    setTimeout(() => {
        document.getElementById("waifu").style.bottom = 0;
        document.getElementById("waifu").style.right = 0;
        document.getElementById("waifu").style.zIndex = 1;
        document.getElementById("waifu").style.position = "fixed";
      }, 0);
    loadLive2d({
        canvas: "live2d",
        baseUrl: "https:\/\/cdn.jsdelivr.net/gh/fghrsh/live2d_api/model/HyperdimensionNeptunia/nepnep",
        model: "https:\/\/cdn.jsdelivr.net/gh/fghrsh/live2d_api/model/HyperdimensionNeptunia/nepnep/index.json",
        width: "300",
        height: "415"
      })
  }'
></script>
```

**Comment by stevenjoezhang** [comment]
你这不都已经实现了 😂 自己用就好了嘛

**Comment by wu-kan** [comment]
> 你这不都已经实现了 😂 自己用就好了嘛

所以是建议嘛😂

**Comment by stevenjoezhang** [comment]
嗯，等我有时间会把现有的加载逻辑修改一下～

**Comment by stevenjoezhang** [comment]
取消注释 cdnPath 选项即可。 https://github.com/stevenjoezhang/live2d-widget/commit/eb8cfab425d04312e62990f70db4fe3f23b083a9
可以把 fghrsh/live2d_api fork 一份自己修改。

**Comment by stevenjoezhang** [comment]
@wu-kan 我确认了一下后台的源代码，其实就是通过302重定向用的jsDelivr的CDN。

> 可以通过jsdelivr之类的cdn加速live2d贴图的访问

这个只能说你多虑了。

<img width="714" alt="截屏2020-02-20下午12 51 57" src="https://user-images.githubusercontent.com/16272760/74902081-e996ad80-53df-11ea-9613-253ddd74a6de.png">

**Comment by stevenjoezhang** [comment]
@wu-kan 问题解决了吗？

**Comment by stevenjoezhang** [comment]
现在已改为默认通过 jsDelivr 的 CDN 加载，代替原有的 API。
