### ISSUE TITLE
浏览器报:initWidget is not defined

### ISSUE THREAD

**Issue by sensune** [stevenjoezhang/live2d-widget#2]
您好，我把live2d_path设置成我服务器上的live2d-widget的路径，而且也能在浏览器上访问到live2d.min.js和waifu-tips.js这两个js文件，但是浏览器却报报了三个错误：
Uncaught SyntaxError: Unexpected token return
Uncaught SyntaxError: Unexpected token this
Uncaught ReferenceError: initWidget is not defined
我把live2d_path换成了https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget/能成功显示，博客是用hexo+next7.1主题

**Comment by stevenjoezhang** [comment]
有点奇怪的bug，能否提供一下网页的链接？

**Comment by sensune** [comment]
> 有点奇怪的bug，能否提供一下网页的链接？

https://clannad.io

**Comment by stevenjoezhang** [comment]
似乎是这个js文件的内容出错了：
https://clannad.io/live2d/waifu-tips.js
里面有乱码，可以检查一下，或许是字符集造成的问题

**Comment by sensune** [comment]
> 似乎是这个js文件的内容出错了：
> https://clannad.io/live2d/waifu-tips.js
> 里面有乱码，可以检查一下，或许是字符集造成的问题

呃, 我进服务器clone项目可以显示了, 不过浏览器访问js文件还是乱码的, 不过能正常显示就可以了, 真搞不明白从本地windows通过git部署到服务器上怎么就出问题了..

**Comment by sensune** [comment]
应该是git提交换行符的问题, 设置了git config --global core.autocrlf false好像解决了

**Comment by stevenjoezhang** [comment]
我的锅，现在应该没问题了： https://github.com/stevenjoezhang/live2d-widget/commit/e89dde2466c58ba1f1fb08062ec1d8a21bdba740

之前的换行符是CRLF
