### ISSUE TITLE
无论按照说明进行fork或自己架设，打开自己网站后只能显示菜单栏，人物不显示

### ISSUE THREAD

**Issue by TaylorLottner** [stevenjoezhang/live2d-widget#20]
[只有用您的cnd才能加载人物，fork到自己的GitHub里面把username换了自己的不显示，一换成您的瞬间显示，已附图。](http://47.95.121.139/wp/wp-content/uploads/2020/02/example.png)

**Comment by TaylorLottner** [comment]
点击评论即可转到图片

**Comment by stevenjoezhang** [comment]
图片不能看出什么……方便给个链接么。
最近更新过一些代码，所以 jsdelivr 可能需要一些时间刷新缓存。

**Comment by stevenjoezhang** [comment]
或者把加载的链接换成这个试试
https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/autoload.js

用户名也对应的替换一下

**Comment by stevenjoezhang** [comment]
jsdelivr 已刷新缓存，此问题自动解决。
