### ISSUE TITLE
在本地服务器已经部署了所有文件，也已配置好，但加载后还是没有效果

### ISSUE THREAD

**Issue by TaylorLottner** [stevenjoezhang/live2d-widget#21]
看板娘是可以加载出来的，但是对于看板娘的设置已经进行修改(如说的话和大小)，可是依旧和你的GitHub里的源码原配置相同，说的话还是没变。附上地址:http://47.95.121.139/wp/
缓存也经过刷新了。。。没用。。。
还有想问一下如何设置大小才能使手机也显示看板娘:https://2heng.xin/👈像这个
麻烦作者了

**Comment by ligyDt** [comment]
你好我刚才查看了下，你的看板娘加载资源404先检查下路径是否正确，看是否能通过网页可以访问到js文件。
![0000](https://user-images.githubusercontent.com/19182390/74898649-74be7600-53d5-11ea-81f6-1a0eb2e056eb.jpg)

**Comment by TaylorLottner** [comment]
你好，可以的http://47.95.121.139/wp/live2d-widget/autoload.js

**Comment by TaylorLottner** [comment]
其他文件也都可以，我打开了根目录了http://47.95.121.139/wp/live2d-widget/其中文件均可访问

**Comment by ligyDt** [comment]
autoload.js 中 `live2d_path` 是否已变更为服务器相对资源路径；
如果你需求简单的话也可以直接引用以下进行直接实现：
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css">
<script src="https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/autoload.js"></script>

**Comment by TaylorLottner** [comment]
以上方法都尝试过，仍然是这样，相对路径已替换

**Comment by TaylorLottner** [comment]
刷新了CDN缓存，可以解决问题了。但还想请问如何使手机也可以显示看板娘，麻烦了！

**Comment by stevenjoezhang** [comment]
移除这个 if 判断

https://github.com/stevenjoezhang/live2d-widget/blob/a4f1df83f89b55ebb547ce50003f7fc69d1b5d52/autoload.js#L28

你给的 IP 地址访问不了，无法帮助 debug。

**Comment by TaylorLottner** [comment]
谢谢帮助！
抱歉，博客被攻击了，数据损坏，正在修复。
今天下午就继续解决

**Comment by TaylorLottner** [comment]
移除
 if (screen.width >= 768) {  是吧{}内的内容全部都删掉吗
