### ISSUE TITLE
live2d 切换人物模型资源加载问题

### ISSUE THREAD

**Issue by ligyDt** [stevenjoezhang/live2d-widget#22]
问题：waifu-tips.js 进行资源加载时error ！
如图所示：
![live2d source Loading problem ](https://user-images.githubusercontent.com/19182390/74898846-10e87d00-53d6-11ea-9a34-c46cf19cb141.jpg)
加载模型：Live2D 模型 6-0 加载完成后出现错误
html page error msg ：
Package size exceeded the configured limit of 50 MB. Try https://github.com/fghrsh/live2d_api/tree/1.0.0/model/HyperdimensionNeptunia/nepnep/general/pose.json instead.
已尝试解决方案：
切换文件内部资源加载链接为本地：
42行 script.src = "https://cdn.jsdelivr.net/gh/GalaxyMimi/CDN/asteroids.js";
54行 open("https://github.com/stevenjoezhang/live2d-widget");
仍未解决；分析原因可能不是因为这两份资源导致。
如大佬有时间请看一下是否能处理，不胜感激。
说明：通过demo进行测试人物切换一样的问题。

**Comment by stevenjoezhang** [comment]
能提供一下你的网页链接么？截图提供的信息有限。

**Comment by ligyDt** [comment]
不好意思，目前是本地调试，还没打包上服务器。
我是按照顺序切换模型的，当切换至模型6时就出现资源403问题。
您可以下载demo在本地测一样的结果，demo1；
我这边环境为 macOS Mojave 10.14.3 目前 测试了两款浏览器：google、Microsoft Edge 均浮现，我觉得可能是因为加载了人物说话声音的资源导致的。因为不发声的人物没有问题

**Comment by stevenjoezhang** [comment]
嗯，确实存在问题。请在这里提Issue： https://github.com/fghrsh/live2d_api

**Comment by ligyDt** [comment]
好的

**Comment by stevenjoezhang** [comment]
已修复，更新后端 API 即可： https://github.com/fghrsh/live2d_api/commit/439a60c8c12b4bd687242524307d80cef2a214fa

**Comment by ligyDt** [comment]
收到，非常感谢您在百忙之中抽取时间解决问题。
