### ISSUE TITLE
使用自己的live2d_api无法加载图片

### ISSUE THREAD

**Issue by SakuraChanNya** [stevenjoezhang/live2d-widget#24]
①live2d_api是直接clone https://github.com/fghrsh/live2d_api.git 的，地址是https://live2dapi.teriri.cc/
②使用原来的apiPath=https://live2d.fghrsh.net/api/可以正常加载图片
![image](https://user-images.githubusercontent.com/29686930/75865825-15358100-5e3f-11ea-8091-773637b0448a.png)
![image](https://user-images.githubusercontent.com/29686930/75865876-27afba80-5e3f-11ea-9f1b-0555138a390a.png)
③但使用自己的api，就无法加载：
![image](https://user-images.githubusercontent.com/29686930/75866135-94c35000-5e3f-11ea-91d6-b6b14791186c.png)
![image](https://user-images.githubusercontent.com/29686930/75866031-66457500-5e3f-11ea-8bc2-07e5f0909204.png)

**Comment by stevenjoezhang** [comment]
<img width="1790" alt="截屏2020-03-04下午6 18 51" src="https://user-images.githubusercontent.com/16272760/75869521-a529f980-5e44-11ea-903d-7f2110f8870a.png">
跨域问题，请正确设置服务器的 HTTP response header。

**Comment by SakuraChanNya** [comment]
> <img alt="截屏2020-03-04下午6 18 51" width="1790" src="https://user-images.githubusercontent.com/16272760/75869521-a529f980-5e44-11ea-903d-7f2110f8870a.png">
> 
> 跨域问题，请正确设置服务器的 HTTP response header。

好的喵！
