### ISSUE TITLE
WordPress 无法显示看板娘, 但是在 F12 控制台中显示加载已完成而且有连接请求.

### ISSUE THREAD

**Issue by Never2333** [stevenjoezhang/live2d-widget#25]
[header.zip](https://github.com/stevenjoezhang/live2d-widget/files/4303071/header.zip)
这是我主题的 header.php.
附上 F12 截图和运行环境:
![QQ截图20200308182508](https://user-images.githubusercontent.com/33362783/76161037-80969000-616a-11ea-9839-92de7fda6d69.png)
![QQ截图20200308182720](https://user-images.githubusercontent.com/33362783/76161039-855b4400-616a-11ea-82a4-6c61df0493eb.png)
![QQ截图20200308182622](https://user-images.githubusercontent.com/33362783/76161041-85f3da80-616a-11ea-9c40-d4403912f6c9.png)

感谢 dalao.

**Comment by stevenjoezhang** [comment]
无法复现。请提供更多信息，比如你的网站的链接。

**Comment by Never2333** [comment]
> 无法复现。请提供更多信息，比如你的网站的链接。
[never666.uk](url)

**Comment by stevenjoezhang** [comment]
它被一个 z-index 更高的元素挡住了。加一行 CSS
```css
#waifu {
  z-index: 1000 !important;
}
```

**Comment by Never2333** [comment]
> 它被一个 z-index 更高的元素挡住了。加一行 CSS
> 
> ```css
> #waifu {
>   z-index: 1000 !important;
> }
> ```

可以了. 感谢.
