### ISSUE TITLE
live2d使用的谷歌字体api失效

### ISSUE THREAD

**Issue by SinonJZH** [stevenjoezhang/live2d-widget#26]
使用live2d之后，由于其中调用的谷歌字体api无法使用，导致网站加载速度被拖慢，在文件中也没有找到是什么代码请求了谷歌字体api，所以想请来问如何关闭谷歌字体api请求。

**Comment by DavidRicardoWilde** [comment]
要复制完整的issues错误信息，再来提issues。
如果真的这个项目请求了，应该可以通过console看到是哪个js调用的，应该不是这个项目

**Comment by stevenjoezhang** [comment]
是的，本项目没有使用谷歌字体。请控制变量来定位问题。

**Comment by SinonJZH** [comment]
抱歉打扰了QAQ，确实不是这个项目的调用，chrome控制台的溯源可能有些问题……

**Comment by stevenjoezhang** [comment]
没事，有其他问题欢迎提出～
