### ISSUE TITLE
有没有大佬把模型移到网页的右下角去的呀

### ISSUE THREAD

**Issue by wallleap** [stevenjoezhang/live2d-widget#28]
改到右下角是要改css对嘛，代码量多吗

**Comment by hjiog** [comment]
稍微改一下，搞定～  
![image](https://user-images.githubusercontent.com/42141272/77304081-e9673600-6d2e-11ea-86d4-bc301987e01e.png)

**Comment by wallleap** [comment]
> 稍微改一下，搞定～
> ![image](https://user-images.githubusercontent.com/42141272/77304081-e9673600-6d2e-11ea-86d4-bc301987e01e.png)

感谢老哥，等下去试下

**Comment by stevenjoezhang** [comment]
这个 Issue 先关了，有其他问题欢迎提出～
