### ISSUE TITLE
请问 Breath.mtn 是什么东东？

### ISSUE THREAD

**Issue by janzzhang** [stevenjoezhang/live2d-widget#3]
您好 在console看到很多类似Breath5.mtn 的302重定向，请问这是做什么用的呀。谢谢~
![image](https://user-images.githubusercontent.com/18203743/57827432-e4b22700-77d9-11e9-9724-168b88a30811.png)

**Comment by stevenjoezhang** [comment]
这个是用来设定看板娘的动作的，比如眨眼睛、摇头。比较奇怪的是这些文件没有缓存，每次都是一个新的http请求……

**Comment by janzzhang** [comment]
> 这个是用来设定看板娘的动作的，比如眨眼睛、摇头。比较奇怪的是这些文件没有缓存，每次都是一个新的http请求……

多谢~ 只是好奇为什么会有302 重定向

**Comment by stevenjoezhang** [comment]
302 重定向应该是为了用上 jsDelivr 的 CDN

**Comment by stevenjoezhang** [comment]
最近我进行了大范围的代码重构，现在可以用上缓存了，不会再出现很多http请求，欢迎试用
