### ISSUE TITLE
想请教一下canvas外事件响应和loadlive2d的实现

### ISSUE THREAD

**Issue by xiaoguai0992** [stevenjoezhang/live2d-widget#30]
Hi,
我想请教一下您项目里的live2d canvas上事件响应的实现：如何让鼠标移出canvas后live2d角色的目光依然能跟随光标运动。
另外，waifu-tips.js中的loadlive2d是否是live2d.min.js中的函数。我在您的代码中没有找到对应的实现。live2d的事件响应是在这里做的吗？
谢谢！

**Comment by stevenjoezhang** [comment]
您好，loadlive2d 是 live2d.min.js 中的。事件响应参考的是这个仓库： https://github.com/EYHN/hexo-helper-live2d
这个我没有具体研究。
