### ISSUE TITLE
请问如何更改模型上下左右偏移量？

### ISSUE THREAD

**Issue by zckBLONGER** [stevenjoezhang/live2d-widget#31]
模型把按钮挡住了

**Comment by stevenjoezhang** [comment]
可以改按钮的位置：
https://github.com/stevenjoezhang/live2d-widget/blob/fde5f1109ef6eec78e39844ef9b19783d353cf8d/waifu.css#L87

**Comment by zckBLONGER** [comment]
> 
> 
> 可以改按钮的位置：
> 
> https://github.com/stevenjoezhang/live2d-widget/blob/fde5f1109ef6eec78e39844ef9b19783d353cf8d/waifu.css#L87

谢谢您的回答！
