### ISSUE TITLE
报错 SyntaxError: JSON Parse error: Unrecognized token '<'

### ISSUE THREAD

**Issue by lei2rock** [stevenjoezhang/live2d-widget#33]
我按照你的说明在 Hexo NexT 的 `source/_data/head.swig` 中添加了相关的代码
```
<script src="/live2d/autoload.js"></script>
```

也修改了autoload.js相应的 `live2d-path` 路径
```
const live2d_path = "/live2d/";
```

把 [fghrsh/live2d_api/](https://github.com/fghrsh/live2d_api/) 的代码部署到了有 Nginx 和 PHP 环境的服务器上建立了[api](https://api.dlzhang.com/live2d) ，但是浏览器依然报错如下，请问是哪里配置还需要修改吗？
![Xnip2020-04-09_17-16-58](https://user-images.githubusercontent.com/19180725/78879048-edf95180-7a85-11ea-9b80-63b584ec5ce6.jpg)
看板娘也无法正确加载
![Xnip2020-04-09_17-19-54](https://user-images.githubusercontent.com/19180725/78879372-62cc8b80-7a86-11ea-97f4-cf4087d19c47.jpg)

**Comment by stevenjoezhang** [comment]
提供的信息有限。仅从截图判断，看上去符合这种情况
<img width="1462" alt="截屏2020-04-09 下午5 55 23" src="https://user-images.githubusercontent.com/16272760/78882865-4b43d180-7a8b-11ea-8b8c-b7394b3103d4.png">
设置 `skip_render` 试试。

**Comment by lei2rock** [comment]
我已经按照要求添加了，还是不行，下面这个是我进行测试的commit，api代码和 fghrsh/live2d_api/ 的代码一样

https://github.com/lei2rock/blog/commit/cb87197953d16887b59be49e41464e98d687b8b8

**Comment by lei2rock** [comment]
好像Chrome下可以正常加载，然后可能是我没有清除缓存，我在Safari的无痕模式下显示正常，我再测试一下，还有问题再反馈给你。谢谢！

**Comment by stevenjoezhang** [comment]
好的，最近更新过，确实可能有缓存问题。谢谢反馈。

**Comment by lei2rock** [comment]
经过测试没有问题可以加载了，不过有个地方还有疑问，需要请教：

目前鼠标指向大部分的网页内容看板娘都会根据 `waifu-tips.json` 设置有反应（目前我还未修改过里面的内容，指已默认设置那些部分）。

但是当鼠标指针放在导航栏目录链接的时候却是没有反应的（ `waifu-tips.json` 中已默认设置的那些），只对分类、标签这两个有反应，其他如首页、归档、搜索等都没有反应，这个问题好像也出现在你的博客里，请问是什么原因？

[我的博客源代码](https://github.com/lei2rock/blog/)

**Comment by stevenjoezhang** [comment]
现在应该好了： https://github.com/stevenjoezhang/live2d-widget/commit/359b1186cd8885c01030c999ff4a01cd9130c0a9
