### ISSUE TITLE
点击拍照没有反应

### ISSUE THREAD

**Issue by crowya** [stevenjoezhang/live2d-widget#35]
点击照相图标后没有下载图片

**Comment by stevenjoezhang** [comment]
换个浏览器试试。

**Comment by crowya** [comment]
试了edge 和 chrome 都不行。浏览器进度条有动一下，但就是没有下载图片。

**Comment by stevenjoezhang** [comment]
提供一下网站的链接？

**Comment by crowya** [comment]
> 提供一下网站的链接？

https://crowdrink.com/

**Comment by stevenjoezhang** [comment]
<img width="793" alt="截屏2020-04-13 下午8 59 14" src="https://user-images.githubusercontent.com/16272760/79122164-a4806d80-7dc9-11ea-856c-8162ff095333.png">

下载图片的默认行为被网页上名为 `argontheme.js` 的脚本所改变。这个 bug 与本插件无关，恐怕我无法解决这个问题。仅从报错信息上来看，似乎是 pjax 错误地处理了图片下载链接。

**Comment by crowya** [comment]
好的，非常感谢，我再想想办法

**Comment by stevenjoezhang** [comment]
嗯，「拍照」的原理就是创建一个指向图片的链接，这个链接带有「download」属性，因此点击它的时候会下载图片。可能是 pjax 监听了全部的链接点击事件造成的问题。

**Comment by crowya** [comment]
顺……顺便再问一下大佬，右键显示一段消息的js应该怎么写，我这样写的好像没用：
`//右键菜单
$("#live2d").mousedown(function(e) {
        if(e.which==3){
        showMessage("秘密通道:<br/><a href=\"https://crowdrink.com\" title=\"首页\" target=\"_blank\">首页</a><a href=\"https://crowdrink.com/wplogin\" title=\"后台\" target=\"_blank\">后台</a><a href=\"http://101.133.211.86\" title=\"宝塔\" target=\"_blank\">宝塔</a> ",10000,1);
		}
});

$("#live2d").bind("contextmenu", function(e) {
    return false;
});`

**Comment by stevenjoezhang** [comment]
`showMessage` 并不是全局的，所以可能访问不到。
https://github.com/stevenjoezhang/live2d-widget/blob/4e27c54ba5705813f0af3c83aa457824f9475e94/waifu-tips.js#L139
试试把 `waifu-tips.js` 中的这一行代码改为
```
window.showMessage = function(text, timeout, priority) {
```

**Comment by crowya** [comment]
虽然右键快捷入口的问题还没有解决，但是拍照的问题解决了，注释掉了argontheme.js中一个名为removeUrlHash(url)的函数后可以正常下载图片了，开心！感谢大佬指出问题所在。
