### ISSUE TITLE
请问如何用代码控制动作?

### ISSUE THREAD

**Issue by lixplor** [stevenjoezhang/live2d-widget#37]
我想用代码控制看板娘的动作, 比如什么时候说话, 往哪里看. 这个是在`live2d.min.js`中的函数来控制的吗? 是否有未压缩版本的? 
谢谢

**Comment by stevenjoezhang** [comment]
你好，未压缩版本请参考 https://github.com/stevenjoezhang/live2d-widget#%E6%9B%B4%E5%A4%9A-more

**Comment by lixplor** [comment]
谢谢!

**Comment by lixplor** [comment]
http://sites.cybernoids.jp/cubism2_cn/ 文档中有提及, 不过是cpp代码, 和js的函数名一样
