### ISSUE TITLE
网页侧边栏展开时会挡住模型，请问应该如何修改？

### ISSUE THREAD

**Issue by acha666** [stevenjoezhang/live2d-widget#38]
![image](https://user-images.githubusercontent.com/37405625/80270021-4fa4f700-86e7-11ea-8e8e-a2e2faffb1dc.png)
![image](https://user-images.githubusercontent.com/37405625/80270026-5af82280-86e7-11ea-8bd6-7b6446238d0d.png)
网页是blog.acha666.cn，不知道能不能把模型放到侧边栏之上？

**Comment by stevenjoezhang** [comment]
可以，修改或覆盖 z-index 即可。

**Comment by acha666** [comment]
> 可以，修改或覆盖 z-index 即可。
> 
> 解决方案可参考 [#25 (comment)](https://github.com/stevenjoezhang/live2d-widget/issues/25#issuecomment-596194449)

非常感谢！数值修改为1000后完美解决
