### ISSUE TITLE
看板娘不显示工具栏，只显示模型

### ISSUE THREAD

**Issue by Galaxy-Studio-Code** [stevenjoezhang/live2d-widget#39]
![image](https://user-images.githubusercontent.com/64064866/80273002-1d07f800-8701-11ea-8c02-ebf435dd36c9.png)
不知道为什么不显示工具栏，求大佬指点
控制台加载正常，就是现实大小为0x0
![image](https://user-images.githubusercontent.com/64064866/80273049-97387c80-8701-11ea-8c5e-a6a768008c59.png)
网址：galaxy-studio.ga

**Comment by stevenjoezhang** [comment]
https://github.com/stevenjoezhang/live2d-widget#%E4%BE%9D%E8%B5%96-dependencies

**Comment by Galaxy-Studio-Code** [comment]
感谢大佬，以前旧的博客上没加还正常，换到新的博客上就不行了，一直没有想到是依赖问题，现在看板娘总算回来了

**Comment by stevenjoezhang** [comment]
嗯，因为 Font Awesome 有两个主要的版本，这里就留给用户去选择了
