### ISSUE TITLE
在hexo博客中配置后，没有显示看板娘

### ISSUE THREAD

**Issue by Tangnameless** [stevenjoezhang/live2d-widget#4]
配置过程参考博客
https://blog.pangao.vip/Hexo%E5%8D%9A%E5%AE%A2NexT%E4%B8%BB%E9%A2%98%E7%BE%8E%E5%8C%96%E4%B9%8B%E6%96%B0%E5%A2%9E%E7%9C%8B%E6%9D%BF%E5%A8%98(%E8%83%BD%E8%AF%B4%E8%AF%9D%E3%80%81%E8%83%BD%E6%8D%A2%E8%A3%85)/

调试的时候，各个js文件都能访问到

其次，下载的demo-1.html无法正常显示
而访问README中的demo-1则能正常显示

**Comment by stevenjoezhang** [comment]
能否提供一下您的博客网站链接？

**Comment by Tangnameless** [comment]
暂时解决了，应该是这个教程的作者，写的有些错误。一个是autoload.js的绝对路径问题，一个是没有注明要设置依赖环境。

**Comment by stevenjoezhang** [comment]
如果这个仓库中的文档有描述不清楚的地方，欢迎指出！
