### ISSUE TITLE
控制台显示Refused to apply style

### ISSUE THREAD

**Issue by user-msi** [stevenjoezhang/live2d-widget#40]
![image](https://user-images.githubusercontent.com/64116300/80274668-bd184e00-870e-11ea-975a-19bef546f6dd.png)
控制台显示拒绝应用样式，想问一下大佬是不是不能直接用github上的css文件

**Comment by stevenjoezhang** [comment]
嗯，看上去不行。可以试试使用 jsDelivr 的 CDN。
