### ISSUE TITLE
域名证书过期

### ISSUE THREAD

**Issue by haig233** [stevenjoezhang/live2d-widget#43]
https://live2d.fghrsh.net
域名证书已过期

**Comment by stevenjoezhang** [comment]
暂时的解决方案有：
1. 取消注释这一行：
https://github.com/stevenjoezhang/live2d-widget/blob/325f8615b44511dad2ab5358ac1ddda852460b88/autoload.js#L37
2. 自建后端服务器

**Comment by stevenjoezhang** [comment]
现在应该好了～

**Comment by stevenjoezhang** [comment]
最近我进行了大范围的代码重构，现在使用 `cdnPath` 也可以支持换装了，可以替换后端 API： https://github.com/stevenjoezhang/live2d-widget/commit/5636fe875f4d233f5838e343b833bd8522bf0949
欢迎试用～
