### ISSUE TITLE
怎么改变live2d的尺寸啊

### ISSUE THREAD

**Issue by drowecho** [stevenjoezhang/live2d-widget#45]
document.body.insertAdjacentHTML("beforeend", `<div id="waifu">
			<div id="waifu-tips"></div>
			<canvas id="live2d" width="800" height="800"></canvas>
			<div id="waifu-tool">
				<span class="fa fa-lg fa-comment"></span>
				<span class="fa fa-lg fa-user-circle"></span>
				<span class="fa fa-lg fa-street-view"></span>
				<span class="fa fa-lg fa-camera-retro"></span>
				<span class="fa fa-lg fa-info-circle"></span>
				<span class="fa fa-lg fa-times"></span>
			</div>
		</div>`);

@media (max-width: 768px) {
	#waifu {
		display: none;
	}
}

我改这2个好像都不行啊，大佬，可以解答一下吗，谢谢

**Comment by stevenjoezhang** [comment]
是指修改 canvas 的大小么？需要调整这里的 `width` 和 `height`
https://github.com/stevenjoezhang/live2d-widget/blob/325f8615b44511dad2ab5358ac1ddda852460b88/waifu.css#L74-L79

**Comment by drowecho** [comment]
好的，谢谢

Mimi <notifications@github.com> 於 2020年5月9日 週六 下午5:36寫道：
