### ISSUE TITLE
live2d加载成功不显示图片

### ISSUE THREAD

**Issue by OY6090** [stevenjoezhang/live2d-widget#46]
![image](https://user-images.githubusercontent.com/64689291/82433845-9d353980-9ac4-11ea-84ea-1287234c796e.png)
遇到了这样该这么解决

**Comment by waleslau** [comment]
我这里也是突然没图片了（几天前是有的）

**Comment by DianChiBan** [comment]
这个照片我加载不出来




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"OY"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 晚上6:07
收件人:&nbsp;"stevenjoezhang/live2d-widget"<live2d-widget@noreply.github.com&gt;;
抄送： &nbsp;“ Subscribed” <subscribed@noreply.github.com&gt;;
主题:&nbsp;[stevenjoezhang/live2d-widget] live2d加载成功不显示图片 (#46)





 

 遇到了这样该这么解决
  
— 
您收到此消息是因为您已订阅此线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by stevenjoezhang** [comment]
存在一些跨域问题（response header 无 access-control-allow-origin），暂时的解决方案：
- 使用自建的 api 后端
- 取消这里 `cdnPath` 前的注释
https://github.com/stevenjoezhang/live2d-widget/blob/d8d42be5e7701961148faea9e5b65afde1710d90/autoload.js#L37

**Comment by xiexinhua2006** [comment]
可以在网站（nginx）配置文件下加上
location ~ .*\.(json)?$
    {
        add_header 'Access-Control-Allow-Origin' '*';
    }
解决无Access-Control-Allow-Origin

**Comment by OY6090** [comment]
用这个方法解决了
 （取消这里cdnPath前的注释）

**Comment by OY6090** [comment]
> 存在一些跨域问题（响应标头无access-control-allow-origin），暂时的解决方案：
> 
> * 使用自建的api初步
> * 取消这里`cdnPath`前的注释
>   https://github.com/stevenjoezhang/live2d-widget/blob/d8d42be5e7701961148faea9e5b65afde1710d90/autoload.js#L37

非常感谢

**Comment by OY6090** [comment]
修改后我把它上传github上无法显示看板娘了，这个该这么解决

**Comment by xiaobencong666** [comment]
> 存在一些跨域问题（response header 无 access-control-allow-origin），暂时的解决方案：
> 
> * 使用自建的 api 后端
> * 取消这里 `cdnPath` 前的注释
>   https://github.com/stevenjoezhang/live2d-widget/blob/d8d42be5e7701961148faea9e5b65afde1710d90/autoload.js

**Comment by xiaobencong666** [comment]
非常感谢

**Comment by a2603802339** [comment]
我也没有人物模型，取消注释也不行

**Comment by Yerannnnnn** [comment]
由于modelId使用的是本地缓存（localStorage），切换CDN前后modelId的安排有区别。

所以切换为CDN后，建议尝试清除缓存。

https://github.com/stevenjoezhang/live2d-widget/blob/3cb21305b40ffc30f0c6a7ba47d9361f15b2354b/waifu-tips.js#L206-L214

**Comment by stevenjoezhang** [comment]
如果问题仍然存在，可以提供以下网页链接，我来看看～

**Comment by OY6090** [comment]
![image](https://user-images.githubusercontent.com/64689291/82520565-167d6c80-9b57-11ea-9be0-f27d968eccc5.png)
在本地运行就可以显示
但是一上传gitee上后就不会显示
![image](https://user-images.githubusercontent.com/64689291/82520698-5a707180-9b57-11ea-9232-9bcf73ab841d.png)
这是我的博客地址 https://oy6090.gitee.io/

**Comment by a2603802339** [comment]
> 由于modelId使用的是本地缓存（localStorage），切换CDN前后modelId的安排有区别。
> 
> 所以切换为CDN后，建议尝试清除缓存。
> 
> https://github.com/stevenjoezhang/live2d-widget/blob/3cb21305b40ffc30f0c6a7ba47d9361f15b2354b/waifu-tips.js#L206-L214

可以正常显示了，谢谢ㄟ( ▔, ▔ )ㄏ

**Comment by OY6090** [comment]
> > 由于modelId使用的是本地缓存（localStorage），切换CDN前后modelId的安排有区别。
> > 所以切换为CDN后，建议尝试清除缓存。
> > https://github.com/stevenjoezhang/live2d-widget/blob/3cb21305b40ffc30f0c6a7ba47d9361f15b2354b/waifu-tips.js#L206-L214
> 
> 可以正常显示了，谢谢ㄟ（▔，▔）

**Comment by OY6090** [comment]
> 由于modelId使用的是本地缓存（localStorage），切换CDN前后modelId的安排有区别。
> 
> 所以切换为CDN后，建议尝试清除缓存。
> 
> https://github.com/stevenjoezhang/live2d-widget/blob/3cb21305b40ffc30f0c6a7ba47d9361f15b2354b/waifu-tips.js#L206-L214

已解决，非常感谢

**Comment by OY6090** [comment]
> 如果问题仍然存在，可以提供以下网页链接，我来看看～

目前已解决，非常大佬帮助，谢谢

**Comment by stevenjoezhang** [comment]
现在改为默认通过 jsdelivr 的 CDN 服务加载，应该没问题了

**Comment by Ephemeral-Echo** [comment]
如何设置可以在手机端也显示看板娘呢？小白啥也不会，谢谢🥗

**Comment by wjh31461** [comment]
你好！请问这是什么情况啊
我在vue项目的index.html中引入了线上的autoload.js后，页面报错了
![image](https://user-images.githubusercontent.com/41609334/100427745-e1d20b00-30cd-11eb-898d-456c6a175721.png)
![image](https://user-images.githubusercontent.com/41609334/100427919-265da680-30ce-11eb-9ca7-0e2b9c7c36da.png)

![image](https://user-images.githubusercontent.com/41609334/100428220-9bc97700-30ce-11eb-9a70-adb18808290d.png)
点开看了一下 这里的参数t并不是arraybuffer 所以json.parse('')报错了

请问这是什么原因啊 我自己新建了个单独的html文件引入后打开后并没有报错

**Comment by stevenjoezhang** [comment]
如果遇到网络问题，可以换一个 CDN 提供商试试
