### ISSUE TITLE
看板娘位置设置在右边后不显示工具栏

### ISSUE THREAD

**Issue by dave0824** [stevenjoezhang/live2d-widget#47]
在waifu.css中设置了
`
#waifu {
	bottom: -1000px;
	right: 0; // 让看板娘出现在最右侧
	line-height: 0;
	margin-bottom: -10px;
	position: fixed;
	transform: translateY(3px);
	transition: transform .3s ease-in-out, bottom 3s ease-in-out;
	z-index: 1;
}

#waifu-tool {
	color: #aaa;
	opacity: 0;
	position: absolute;
	left: 10px; // 设置工具栏在左侧显示
	top: 70px;
	transition: opacity 1s;
}
`
后访问只在右侧加载了看板娘，不能加载工具栏。求助。

**Comment by stevenjoezhang** [comment]
加载了 Font Awesome 么？

**Comment by dave0824** [comment]
> 加载了 Font Awesome 么？

您好，加载了的，如下
`
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css">
`

**Comment by dave0824** [comment]
> 加载了 Font Awesome 么？
您好，加载了的：
`
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css">
`

**Comment by dave0824** [comment]
> 加载了 Font Awesome 么？

您好，加载了的：<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css">

**Comment by dave0824** [comment]
‘
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css">
’

**Comment by dave0824** [comment]
‘’’ html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css">
‘’‘’

**Comment by dave0824** [comment]
`
link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css"
`

**Comment by stevenjoezhang** [comment]
能否提供一下网站的链接？

**Comment by dave0824** [comment]
[网站链接：](https://dave0824.github.io/)
[fork您项目的地址：](https://github.com/dave0824/live2d-widget)
谢啦~

**Comment by stevenjoezhang** [comment]
你好，看上去是由于语法问题。CSS 不支持 `//` 注释
```
// 让看板娘出现在最右侧
/* 让看板娘出现在最右侧 */
```
改一下就好了。

**Comment by dave0824** [comment]
> 你好，看上去是由于语法问题。CSS 不支持 `//` 注释
> 
> ```
> // 让看板娘出现在最右侧
> /* 让看板娘出现在最右侧 */
> ```
> 
> 改一下就好了。

您好，还是不行噢。

**Comment by dave0824** [comment]
> > 你好，看上去是由于语法问题。CSS 不支持 `//` 注释
> > ```
> > // 让看板娘出现在最右侧
> > /* 让看板娘出现在最右侧 */
> > ```
> > 
> > 
> > 改一下就好了。
> 
> 您好，还是不行噢。

问题解决了。我重新clone了一份覆盖，然后解决问题了，可能之前不知道哪里被我不小心改动了。。
麻烦您了，十分感谢~

**Comment by stevenjoezhang** [comment]
没事，问题解决了就好～
