### ISSUE TITLE
Chrome调试报错：autoload.js:26 Uncaught ReferenceError: initWidget is not defined

### ISSUE THREAD

**Issue by yyb1995** [stevenjoezhang/live2d-widget#5]
作者大大您好，我在使用插件的过程中遇到了以下问题：在使用您提供的地址
>//const live2d_path = "https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget/";

时看板娘可以正常显示，但是我把您的资源完整拷贝了一份到我的仓库中，改成了
>const live2d_path = "./live2d-widget/"，

看板娘就无法正确显示了。Chrome调试报错：
>autoload.js:27 Uncaught ReferenceError: initWidget is not defined
>Uncaught SyntaxError: Unexpected token return
>ncaught SyntaxError: Unexpected token this

我发现之前也有人问过这个问题，不过我试了一下他的方法，还是不行。请问您知道是怎么回事吗？我的博客地址是：[Eric_fish's Blog](https://yyb1995.github.io/)

**Comment by stevenjoezhang** [comment]
由于未知原因，您的仓库（ https://github.com/yyb1995/yyb1995.github.io ）中的`waifu-tips.js`和`live2d.min.js`包含错误的内容（例如`waifu-tips.js`第7行多了两个引号），导致了语法错误。请重新下载一下。

**Comment by yyb1995** [comment]
回复的好及时，问题完美解决了，谢谢作者大大。给其他人提个醒，在Win10平台下使用Hexo可能会出现这个问题。

**Comment by stevenjoezhang** [comment]
OK，我把这个提醒加到文档里了

**Comment by yyb1995** [comment]
由于上传不方便调试，我下午找了一下，发现好像是Hexo的锅，它似乎会悄悄替换某些js文件中的东西：[Hexo altering Javascript files on generate](https://github.com/hexojs/hexo/issues/1591)。所以解决办法是：在根目录下的配置文件`_config.yml`中加入
```yml
skip_render:
  - '/live2d-widget/**'
```
即可，就是不让Hexo对live2d动手脚了。目录就是相对于根目录live2d文件的目录。这样无论是`hexo s`还是`hexo d`看板娘都可正确显示~

**Comment by stevenjoezhang** [comment]
Hexo 应该修复了这个问题。
