### ISSUE TITLE
为什么会同时加载两个看板娘

### ISSUE THREAD

**Issue by v-tawe** [stevenjoezhang/live2d-widget#52]
我是把项目clone到 hexo 主题里的，用相对路径加载后怎么 左右 会各有一个看板娘？ 大神帮忙看看：
![image](https://user-images.githubusercontent.com/22313449/89102343-ded64f00-d43a-11ea-8587-4d07c4bc30aa.png)

**Comment by stevenjoezhang** [comment]
1. 在你的 Hexo 根目录下执行 `npm ls --depth 0`
2. 找到其中全部包含 `live2d` 的项目，通过 `npm uninstall` 命令卸载
3. 执行 `hexo clean`
