### ISSUE TITLE
使用了自己上传npm的包，看板娘变模糊了

### ISSUE THREAD

**Issue by zhengli233** [stevenjoezhang/live2d-widget#53]
我按照示例说的fork了一份到自己的repo中，使用jsdelivr去加载js脚本，但是发现做了更改后，jsdelivr不更新，仍然使用老的缓存，所以后来打包到npm上，让jsdelivr读npm的包，这样可以及时更新，但发现和原来比，看板娘变模糊了，没弄懂是为什么。
我只是把看板娘挪到了右侧。

应用的网址是
https://blog.houtiao.club
大神能帮忙看看吗？

**Comment by stevenjoezhang** [comment]
看板娘的分辨率在这个 commit 里调整过： https://github.com/stevenjoezhang/live2d-widget/commit/651b0fefa6438b9f97d481a9c91464bde6ba0120
可以检查一下有关代码

**Comment by zhengli233** [comment]
解决了，感谢！
