### ISSUE TITLE
Font Awesome 的 js 使按钮点击无反应

### ISSUE THREAD

**Issue by 1537069101** [stevenjoezhang/live2d-widget#54]
![image](https://user-images.githubusercontent.com/65661460/100542033-b47a8e00-3282-11eb-8710-649e4242572c.png)

**Comment by PFiS1737** [comment]
这个按钮的位置就不对，建议检查一下waifu-tips.js文件

**Comment by stevenjoezhang** [comment]
能提供一下网页链接嘛？

**Comment by stevenjoezhang** [comment]
已完成重构。现在本插件不再需要用户手动引入 Font Awesome 的 css，也不会与页面上 Font Awesome 相关的 css 或 js 冲突。见： https://github.com/stevenjoezhang/live2d-widget/commit/abb832a9ea3f006b7d8b9c0567bba99c5603b426
