### ISSUE TITLE
demo.html页面点击换装按钮无效

### ISSUE THREAD

**Issue by yuang01** [stevenjoezhang/live2d-widget#58]

**Comment by PFiS1737** [comment]
可能是因为jsDelivr对文件大小的限制，大于50M的文件不能正常引用(只是推测)。
可以在配置时使用`apiPath`就行解决。

**Comment by stevenjoezhang** [comment]
考虑到访问量较大，示例页面通过 CDN 加载，因此存在这一限制。
自己使用时，建议搭建后端并配置 `apiPath`。
