### ISSUE TITLE
暗色主题的博客看不清字

### ISSUE THREAD

**Issue by sensune** [stevenjoezhang/live2d-widget#61]
不知道是透明度还是字体颜色的问题，暗色主题的博客会看不见字，请问是需要修改哪里吗
![image](https://user-images.githubusercontent.com/39215710/106867750-eee02b80-6708-11eb-9f74-ca4242e26ad7.png)

**Comment by stevenjoezhang** [comment]
<img width="323" alt="截屏2021-02-04 下午4 53 23" src="https://user-images.githubusercontent.com/16272760/106868243-804f9d80-6709-11eb-99af-19a822f89aa2.png">

我的是正常的。从你的截图来看，字体颜色似乎被页面上的什么别的样式覆盖了。

**Comment by sensune** [comment]
哎，看不懂前端，找了半天，算是找到了，好像是被一个body{color: }的颜色导致的，加了个#waifu-tips的color算是解决了

**Comment by stevenjoezhang** [comment]
问题解决了就好～

如果有什么别的疑问，可以提供一下网站的链接，我帮忙看看
