### ISSUE TITLE
Are derivative open source projects also required to license under GPL-3.0 License?

### ISSUE THREAD

**Issue by KnowsCount** [stevenjoezhang/live2d-widget#62]
Hi Steven,
I realised there is a licensing restriction since you talked to me about it in our prior email conversations, so I hereby ask whether my project [qiokian](https://github.com/KnowsCount/qiokian) has violated the live2d official rules or not. I used MIT licence.

**Comment by Dream3-of-flowers** [comment]
unsubscribe------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;KnowsCount&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月13日(星期六) 晚上11:00
收件人:&nbsp;&quot;stevenjoezhang/live2d-widget&quot;<live2d-widget@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[stevenjoezhang/live2d-widget] Are derivative open source projects also required to license under GPL-3.0 License? (#62)

**Comment by KnowsCount** [comment]
I'm sorry... I cannot comprehend. Wdym?
