### ISSUE TITLE
请问能否增加一个拖拽移动看板娘的功能？

### ISSUE THREAD

**Issue by Immortal68** [stevenjoezhang/live2d-widget#65]
Stevenjoezhang您好，
请问后续能否增加一个拖拽移动看板娘的功能？

**Comment by PFiS1737** [comment]
指的是可以左右拖动吗，如果还要可以记住位置的话，做起来有点麻烦。最近repo主基本不在线，如果只是想要让看板娘可以在左下角和右下角切换的话，可以考虑去看看Pull requests里的那个

**Comment by Immortal68** [comment]
> 指的是可以左右拖动吗，如果还要可以记住位置的话，做起来有点麻烦。最近repo主基本不在线，如果只是想要让看板娘可以在左下角和右下角切换的话，可以考虑去看看Pull requests里的那个

谢谢，已经用上Pull requests那个了

**Comment by stevenjoezhang** [comment]
近期会将拖拽移动看板娘的功能加上，感谢各位关注。

**Comment by stevenjoezhang** [comment]
感谢建议，已增加拖动功能 https://github.com/stevenjoezhang/live2d-widget/commit/aae552759611e205fb8d5a49f0349f2630bc0d1c
