### ISSUE TITLE
请问js一直404是什么问题？

### ISSUE THREAD

**Issue by Immortal68** [stevenjoezhang/live2d-widget#68]
之前安装之后一直没问题，这次按同样方法安装了一遍，js一直404，看板娘加载不出来，求解答，感谢

**Comment by stevenjoezhang** [comment]
能提供一下网页链接嘛？

**Comment by Immortal68** [comment]
> 能提供一下网页链接嘛？

http://ultradream.jxpassword.top/，麻烦了~

**Comment by Immortal68** [comment]
> 能提供一下网页链接嘛？

http://ultradream.jxpassword.top
麻烦了~

**Comment by stevenjoezhang** [comment]
嗯，我看到是这个文件 404 了  http://ultradream.jxpassword.top/live2d-widget/autoload.js

这是你自己的服务器么？你可以检查一下是不是权限问题，或者 nginx 配置不对？

或者用 cdn 加载也可以，可能还方便些： https://github.com/stevenjoezhang/live2d-widget#using-cdn

**Comment by Immortal68** [comment]
> 嗯，我看到是这个文件 404 了 http://ultradream.jxpassword.top/live2d-widget/autoload.js
> 
> 这是你自己的服务器么？你可以检查一下是不是权限问题，或者 nginx 配置不对？
> 
> 或者用 cdn 加载也可以，可能还方便些： https://github.com/stevenjoezhang/live2d-widget#using-cdn

是我自己的服务器。现在换直接用cdn加载了，恢复正常了，感谢！

**Comment by stevenjoezhang** [comment]
问题解决了就好～
