### ISSUE TITLE
关于看板娘按钮位置更改

### ISSUE THREAD

**Issue by Skrtono** [stevenjoezhang/live2d-widget#7]
我现在实在无法改变按钮的位置，我的播放器挡住了，请问该如何改变按钮位置

**Comment by stevenjoezhang** [comment]
往上面挪了一点：https://github.com/stevenjoezhang/live2d-widget/commit/eb4ca52d732f9d002ebf0e8ad6664c11607d9cd6
通过git更新就行了。有其他问题欢迎提出。

**Comment by Skrtono** [comment]
> 往上面挪了一点：[eb4ca52](https://github.com/stevenjoezhang/live2d-widget/commit/eb4ca52d732f9d002ebf0e8ad6664c11607d9cd6)
> 通过git更新就行了。若有其他问题欢迎提出。

谢谢
