### ISSUE TITLE
想詢問如何在 gatsby 載入

### ISSUE THREAD

**Issue by hakanaku1234** [stevenjoezhang/live2d-widget#71]
https://github.com/gatsbyjs/gatsby

这个项目建的 path 会变成 undefined 找不到原因 请问有人能成功载入吗 🙏 

![image](https://user-images.githubusercontent.com/34119262/114398965-fcb3a080-9bd2-11eb-8184-28b115550282.png)

**Comment by stevenjoezhang** [comment]
原因应该是  `localStorage.getItem("modelId")` 获取到了非法值

**Comment by stevenjoezhang** [comment]
相关代码最近进行了重构，可以解决 `modelId` 非法问题，欢迎试用～
