### ISSUE TITLE
请问为什么放在我的网站上以后会遮住背景动画呀？

### ISSUE THREAD

**Issue by QiuYeDx** [stevenjoezhang/live2d-widget#73]
看起来仿佛是占用了背景的一块儿区域，还不是因为模具不是透明的缘故……很奇怪……请问怎么解决这个问题呢？
具体效果可以看我下我的博客网站 http://39.106.58.123/wp-blog

**Comment by stevenjoezhang** [comment]
<img width="399" alt="截屏2021-04-30 上午2 37 18" src="https://user-images.githubusercontent.com/16272760/116601358-0112e400-a95d-11eb-8b25-7990821e5858.png">

你的网站为所有的 canvas 元素设置了背景颜色。建议将其修改为一个更精确的选择器。

**Comment by QiuYeDx** [comment]
> <img alt="截屏2021-04-30 上午2 37 18" width="399" src="https://user-images.githubusercontent.com/16272760/116601358-0112e400-a95d-11eb-8b25-7990821e5858.png">
> 
> 你的网站为所有的 canvas 元素设置了背景颜色。建议将其修改为一个更精确的选择器。

感谢前辈指点！
