### ISSUE TITLE
怎么往上挪？

### ISSUE THREAD

**Issue by sysdl132** [stevenjoezhang/live2d-widget#75]
![image](https://user-images.githubusercontent.com/54708046/116868586-9e159b80-ac41-11eb-8ca7-0282c9e708f2.png)

怎么上移一层或把这个挪到面板上面( [仓库中的index.html](https://github.com/sysdl132/sysdl132.github.io) )

**Comment by PFiS1737** [comment]
将#waifu的z-index改为更大的值
(#waifu-toggle也最好改一下)
