### ISSUE TITLE
关于人物位置和人物被遮挡

### ISSUE THREAD

**Issue by Skrtono** [stevenjoezhang/live2d-widget#8]
有两位看板娘会浮空，一位位置过下。还有看板娘会被我的首页遮挡

**Comment by stevenjoezhang** [comment]
需要自己搭建API，然后手动调整模型的参数来解决。参考：https://github.com/fghrsh/live2d_api

**Comment by CheneyTran** [comment]
你好，有时候看板娘会不显示只有文字和菜单栏，请问如何调整呢

**Comment by Skrtono** [comment]
> 你好，有时候看板娘会不显示只有文字和菜单栏，请问如何调整呢

可能是缓存问题，我之前也会，后面自动有好了

**Comment by stevenjoezhang** [comment]
是的，默认的后端API访问量有点大，有时候由于网络延迟，看板娘加载较慢

**Comment by ElmTran** [comment]
好像是我fork您的代码，然后引用了我的gh地址，但是cdn没有更新，加载出错了，这会又好了。不过我发现我用的jekyll搭建的博客竟然能直接用，我都以为需要我用hexo先生成插件在引用。谢谢你，有学到东西了。

**Comment by bauLiXin** [comment]
你好，模型文件有吗，可以分享吗？

**Comment by stevenjoezhang** [comment]
@bauLiXin 看README，这几个GitHub仓库里有：https://github.com/stevenjoezhang/live2d-widget#%E9%B8%A3%E8%B0%A2-credits

**Comment by bauLiXin** [comment]
这个live2d.min.js有npm包吗？只能script引入吗。

**Comment by superfeng-99** [comment]
菜单显示不出来 是waifu-tips.json出了问题吗

**Comment by stevenjoezhang** [comment]
菜单需要FontAwesome，可以检查一下。或者发个链接我来看看。

**Comment by xvyourang** [comment]
可以加下拖动功能吗？我自己加算了 - -*

**Comment by stevenjoezhang** [comment]
借助 jQuery UI 等第三方库实现拖动很简单，但使用纯 CSS 和 JS 并不容易优美地完成这个功能。

Talk is cheap. Show me the code.

**Comment by stevenjoezhang** [comment]
如果要改模型的话，可以把 https://github.com/fghrsh/live2d_api fork 一份自己修改。

**Comment by stevenjoezhang** [comment]
最近我进行了大范围的代码重构，现在支持拖动功能了，资源加载也进行了优化，模型加载成功后才会整体滑动进入页面，欢迎试用
