### ISSUE TITLE
随机信息的请求跨域了

### ISSUE THREAD

**Issue by zzzgd** [stevenjoezhang/live2d-widget#80]
点快了就控制台报错说跨域, 不知道这个算不算bug

Access to fetch at 'https://v1.hitokoto.cn/' from origin 'https://zzzgd.info' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

https://v1.hitokoto.cn/

**Comment by stevenjoezhang** [comment]
点快了应该是触发了 https://v1.hitokoto.cn/ 的限制。应该能加一个冷却时间。
