### ISSUE TITLE
那个纸飞机图标, 说要不要玩游戏的, 点完上面出现个倒三角, 然后点击说按esc退出

### ISSUE THREAD

**Issue by zzzgd** [stevenjoezhang/live2d-widget#81]
这个我理解应该是个点击小游戏吧, https://zzzgd.info 我这个点了没反应, 能帮忙看看不

**Comment by PFiS1737** [comment]
要用电脑才能玩，参考http://www.websiteasteroids.com/

**Comment by zzzgd** [comment]
好吧 哈哈哈, 压根不知道怎么玩, 看了才知道是方向键和空格, 我觉得这个提示可以改下
