### ISSUE TITLE
听不见看板娘说话的声音

### ISSUE THREAD

**Issue by wupengbo125** [stevenjoezhang/live2d-widget#86]
之前看到某个博客，看板娘会说话，这个咋能听见声音呢

**Comment by PFiS1737** [comment]
单独的live2d不能播放音频（吧，
如果需要，可以接个朗读api，在显示文字的同时播放录音（

**Comment by krmao** [comment]
@wupengbo125 请问怎么解决的，注意到 cnblog 的看板娘确实有日版声音

**Comment by wupengbo125** [comment]
@krmao 没解决哎，放弃了

**Comment by PFiS1737** [comment]
最新版本的 Live2D Web SDK 中确实支持播放声音，但由于这个包里 live2d.min.js 是封装过的，而且不知道源文件在哪，无法查证有没有这个功能（大概是没有，因为播放声音要 v3 的 SDK ），但可通过添加其他点击事件等来实现有声音的互动。
具体实现方法可以去研究一下 tips.js 的运行方式，并自行添加

**Comment by krmao** [comment]
收到, 还是不搞了吧
