### ISSUE TITLE
修改了您的代码，我的开源协议是否也需要设置为GPL?

### ISSUE THREAD

**Issue by HappyYYT** [stevenjoezhang/live2d-widget#87]
您好，最近在我自己的开源项目[lucky-fairys-lucky-draw](https://github.com/HappyYYT/lucky-fairys-lucky-draw)中使用了对您的项目修改后的代码。[在线版本](https://lucky-fairys-lucky-draw.web.cloudendpoint.cn/)
使用情况如下：
index.html
-js
  --live2d.min.js
  --modified2dLive.js (修改)
请问我的开源协议是否要更改为GPL（现在是MIT）？如果需要，我会立即更改:relaxed:，以及有什么不妥之处希望得到您的指出:chestnut:。
除此之外，我还想知道这是否会“污染”我的后端代码？目前我不太乐意开源这个项目的后端代码。
非常感谢得到您的回复~:grinning:

**Comment by stevenjoezhang** [comment]
您好，非常感谢您对开源协议的关注。创建这个仓库时我是按习惯选择的 GPL 协议，并没有考虑到它会发展得如此受欢迎。从实际的使用情况来看，许多用户都会加入自定义内容，或者修改 CDN 的链接；GPL 协议过于严格了 。我会研究一下是否可以将配置文件独立出来，或者更换较为宽松的开源协议。

**Comment by HappyYYT** [comment]
> 您好，非常感谢您对开源协议的关注。创建这个仓库时我是按习惯选择的 GPL 协议，并没有考虑到它会发展得如此受欢迎。从实际的使用情况来看，许多用户都会加入自定义内容，或者修改 CDN 的链接；GPL 协议过于严格了 。我会研究一下是否可以将配置文件独立出来，或者更换较为宽松的开源协议。

好哒，非常感谢你！:tulip::rose::sunflower::four_leaf_clover::hibiscus::ear_of_rice:

**Comment by stevenjoezhang** [comment]
总的来讲，回到原来的问题，我的理解是：
- 如果您的网页使用了本项目的代码，那么全部的前端源代码均需要以 GPL 协议开源
- 如果网页的后端代码与前端代码没有强耦合，可以视为两个独立的程序，那么不受 GPL 约束

再次感谢各位对开源协议的关注！
