### ISSUE TITLE
萌新请教一下 

### ISSUE THREAD

**Issue by 1752686602** [stevenjoezhang/live2d-widget#88]
我想在手机端出现他 我根据您的回答发现调节最小页面宽度可以出现
但是在哪里调节整体的大小了...很抱歉给您添麻烦了

**Comment by stevenjoezhang** [comment]
是这个 `if` 判断
https://github.com/stevenjoezhang/live2d-widget/blob/f0aa9f30781242540705986bec0973564efd2a7c/autoload.js#L28-L40

**Comment by 1752686602** [comment]
我能把她显示出来..但是大小没办法改变 好像也不是缓存的原因..怎么把她缩小一半呢..呜呜呜呜·

**Comment by PFiS1737** [comment]
在页面加载完成后将 canvas 的长宽调一下就行，比如
```js
window.onload = () => {
    document.getElementById("live2d").style = "width: 200px; height: 200px;"
}
```
其他元素的css根据实际需要，做调整

不知道css是什么的话建议先去学一下

**Comment by stevenjoezhang** [comment]
这个 Issue 先关了，有其他问题欢迎回复～
