### ISSUE TITLE
为live2d增加随机语音选择

### ISSUE THREAD

**Issue by XunZhan** [stevenjoezhang/live2d-widget#89]
你好！我初次接触到live2d所以问的问题可能比较浅显。
我想问如何为自己的模型增加触碰时的语音，如果可以，能不能做到每次相同的触碰从一个语音列表随机选择一段语音播放呢？
我根据代码查看了live2d api的repo不过里面也没有介绍。于是我找到了一个关于live2d配置文件的文档： https://live2d.pavostudio.com/doc/zh-cn/live2d/model-json-example/ 我不知道如果要单纯的增加语音是否是这样做？以及他们的配置方案是不是你们正在用的？其他的配置方法比如亲密度，区域选择是不是也是兼容的？

最后想问，如果可以实现触碰语音，怎么做到随机选择一段语音。是否需要自己添加此功能？谢谢你！

**Comment by krmao** [comment]
@XunZhan 请问有成果吗？分享下

**Comment by krmao** [comment]
@XunZhan 主要是没有好听的语音资源
