### ISSUE TITLE
在今年最新mac电脑上 显示模型 并没有外显上面清晰

### ISSUE THREAD

**Issue by Wangguanxiang4** [stevenjoezhang/live2d-widget#92]

**Comment by stevenjoezhang** [comment]
可以手动增加 canvas 的 width 和 height，以适配像素密度较高的屏幕：
https://github.com/stevenjoezhang/live2d-widget/blob/d3b85540564f8ae5638e785d9b79a596116de34a/waifu-tips.js#L22
