### ISSUE TITLE
显示和性能问题。

### ISSUE THREAD

**Issue by Nesxc** [stevenjoezhang/live2d-widget#93]
如何让手机端不显示live2d，因为我发现手机端加载live2d会造成页面卡顿

**Comment by stevenjoezhang** [comment]
可以基于屏幕宽度判断： https://github.com/stevenjoezhang/live2d-widget/blob/d3b85540564f8ae5638e785d9b79a596116de34a/autoload.js#L28
要求更准确的话可以用 userAgent 判断

**Comment by Nesxc** [comment]
> 可以根据细分判断：
> 
> https://github.com/stevenjoezhang/live2d-widget/blob/d3b85540564f8ae5638e785d9b79a596116de34a/autoload.js#L28
> 
> 
> 要求更准确的话可以使用 userAgent 判断

感谢您的回复，我来修改一下看看效果，我很好奇为什么这个插件在手机端及其的卡顿。

**Comment by PFiS1737** [comment]
不过我这边用着不卡欸 （
