### ISSUE TITLE
开发者您好,人物模型被遮挡的问题

### ISSUE THREAD

**Issue by wjl110** [stevenjoezhang/live2d-widget#96]
开发者您好,我使用的是hexo+vue主题,fork后在主题yml配置文件中引用了您的小部件
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/53851034/158100148-d7070f73-04bd-465e-a971-4cbff6852458.png">

实际网站效果会出现以下情况
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/53851034/158099931-05199829-f6ce-4426-8fc7-f887cc24accf.png">
请问如何jie解决呢?
致-stevenjoezhang

**Comment by stevenjoezhang** [comment]
您好，增加下面这个值：
https://github.com/stevenjoezhang/live2d-widget/blob/d3b85540564f8ae5638e785d9b79a596116de34a/waifu.css#L33
直到人物模型能够覆盖其它组件

**Comment by wjl110** [comment]
这个值原先就已存在,人物依旧置于后方

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/53851034/158102184-e6d45698-eddb-43ed-be11-c8a52b4706bb.png">

**Comment by PFiS1737** [comment]
> 这个值原先就已存在,人物依旧置于后方
> 
> <img alt="image" width="1274" src="https://user-images.githubusercontent.com/53851034/158102184-e6d45698-eddb-43ed-be11-c8a52b4706bb.png">

增加它的数值，将1改为其他更大的数，这个样式是规定它的海拔的（越大，将会被更优先显示

**Comment by wjl110** [comment]
发现了如下几个问题
<img width="890" alt="image" src="https://user-images.githubusercontent.com/53851034/158109289-927fdb59-56b1-4404-ac70-bb5ec44027d5.png">
数值已修改
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/53851034/158109608-19e6a544-0b56-4bc2-b7ec-91fa88cfc4d3.png">

js已经修改
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/53851034/158109222-9b4c7f8d-78c7-4ceb-83b7-427c4068f50d.png">
个人fork地址
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/53851034/158109472-a22fc990-5d8a-4af7-bf79-e149521c3d08.png">
发布的版本号
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/53851034/158109671-0ff0d2c0-23ae-4818-b77c-44a62375f61b.png">
肢体配置文件
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/53851034/158109770-b3610394-c712-40dd-bea7-8b239060c5fc.png">

**Comment by PFiS1737** [comment]
大概是因为 jsdelivr 缓存的问题，建议放到本地，

尝试访问一下 `https://purge.jsdelivr.net/...` 对应的页面 （即把 cdn 改为 purge）多访问几遍

**Comment by wjl110** [comment]
收到 

> 大概是因为 jsdelivr 缓存的问题，建议在本地，
> 
> 试用一下访问一下`https://purge.jsdelivr.net/...`的页面（即把cdn改为purge）多访问几遍

**Comment by wjl110** [comment]
> https://purge.jsdelivr.net/

在本地访问的情况是这样的
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/53851034/158133595-7a988758-08b7-49a4-9c12-67a84159de8f.png">

**Comment by wjl110** [comment]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/53851034/158143827-7829d46d-f8c6-4492-ab5a-cf0cca4d530a.png">


> 大概是因为 jsdelivr 缓存的问题，建议在本地，
> 
> 试用一下访问一下`https://purge.jsdelivr.net/...`的页面（即把cdn改为purge）多访问几遍

**Comment by wjl110** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/53851034/158157502-656ba36d-eb2f-414b-88ce-343be1ad6d14.png">
成功了,我把readme重新读了三遍,确认 是cdn缓存和本地浏览器缓存的问题

**Comment by wjl110** [comment]
谢谢你们的帮助

**Comment by wjl110** [comment]
遗憾的是我将z-z-index的值设置为100,
人物依然后置...♡o(╥﹏╥)o ♥♡
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/53851034/158158730-bce8b3ce-c4ef-4632-bfd8-77cd8a81c8f5.png">

**Comment by wjl110** [comment]
难道是要设置成负数么....

**Comment by wjl110** [comment]
如果您不闲麻烦的话,可以帮我查看一下是哪儿出了问题么...
小组件地址:https://github.com/wjl110/live2d-widget
hexo+机关主题配置文件地址:https://github.com/wjl110/wjl110.github.io/blob/main/_config.aurora.yml
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/53851034/158160929-45d4250f-214d-485d-a4a1-c96fb073db51.png">
cdn缓存地址:https://cdn.jsdelivr.net/gh/wjl110/live2d-widget@1.0.1/autoload.js
<img width="879" alt="image" src="https://user-images.githubusercontent.com/53851034/158161076-204fc190-c8b1-4d4f-91cb-8fb1a1a38fed.png">
小组件缓存地址:https://cdn.jsdelivr.net/gh/wjl110/live2d-widget/
<img width="461" alt="image" src="https://user-images.githubusercontent.com/53851034/158161282-c27ae662-5af6-4d1b-878f-94ef7fa2c861.png">

**Comment by stevenjoezhang** [comment]
100 不够就继续加，加到盖住其它内容为止 😂
上限应该是 2147483647

**Comment by wjl110** [comment]
收到

**Comment by wjl110** [comment]
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/53851034/158172853-34eeb8e8-ce02-405f-84d7-d187c7a4efc5.png">

**Comment by lzhvahaha** [comment]
已经加到2147483647了，还是不行啊

**Comment by wangjunmiao** [comment]
请问博客中的看板娘 怎么做到切换页面人物不重新加载呢

**Comment by PFiS1737** [comment]
> 请问博客中的看板娘 怎么做到切换页面人物不重新加载呢

这个不是看版娘应该设计的功能，而是应该在你的网站中实现，比如 PJAX 可以让在页面不重新加载的情况下更新内容，应该将看板娘放在其加载范围以外的地方
