### ISSUE TITLE
和看板娘互动时的鼠标位置不对

### ISSUE THREAD

**Issue by barryblueice** [stevenjoezhang/live2d-widget#98]
已经添加看板娘了，但是和人物互动的时候触发位置会在人物上方。
网站：www.barryblueice.top

**Comment by barryblueice** [comment]
就是不知道要修改哪一个文件

**Comment by barryblueice** [comment]
而且有时候位置也不对

**Comment by PFiS1737** [comment]
我在你的网站里看到了好live2d相关的文件（而且其中的 message.js 文件还需要 jq，网页中也没有加载），应该只将这个库的 autoload.js 和 Font Awesome 加进网页

**Comment by barryblueice** [comment]
> 我在你的网站里看到了好多 live2d 相关的文件（而且其中的 message.js 文件还需要 jq，网页中也没有加载），应该只将这个库的 autoload.js 和 Font Awesome 加进网页

好的，我试一下

**Comment by barryblueice** [comment]
> 我在你的网站里看到了好多 live2d 相关的文件（而且其中的 message.js 文件还需要 jq，网页中也没有加载），应该只将这个库的 autoload.js 和 Font Awesome 加进网页

谢谢，已经解决了。
还有一个问题就是我的按钮全部变成了方格，请问这个问题有办法解决吗？

**Comment by PFiS1737** [comment]
加载 Font Awesome 了吗？

**Comment by barryblueice** [comment]
> 加载 Font Awesome 了吗？

添加了

**Comment by stevenjoezhang** [comment]
<img width="403" alt="捕获" src="https://user-images.githubusercontent.com/16272760/162136590-1d9cd644-3fab-4117-a6b0-ee59207a14de.PNG">

添加了，但没完全添加。检查一下你的服务器，CORS 设置不对。

**Comment by PFiS1737** [comment]
font-awesome.min.css 的 `@font-face` 中规定的字体文件位置在 "../fonts/" 但实际上，字体文件在 "./fonts/" 的位置，所以不能正确引用，而且在控制台里报错了很多 acao 问题，建议检查一下

**Comment by barryblueice** [comment]
> font-awesome.min.css 的 `@font-face` 中规定的字体文件位置在 "../fonts/" 但实际上，字体文件在 "./fonts/" 的位置，所以不能正确引用，而且在控制台里报错了很多 cors 问题，建议检查一下

好的，我去看看
